### ISSUE TITLE
If you re-run terraform, vpc_net and allocate_new_ip always shows as updating from "" to the same value it was created with in the first run

### ISSUE THREAD

**Issue by infa-apatel** [AviatrixSystems/terraform-provider-aviatrix#264] opened 2019-03-07 23:16 UTC
When I run my terraform code first time, with VPC_NET and allocate_new_eip value, it goes through fine and creates the gateway.  If I re-run my terraform code without any change, it still wants to update the VPC_NET, from "" value to the same value I used the first time.  When you apply terraform anyways, it will fail saying VPC_NET is not allowed to be uddated. 

See example below:

 ~ module.vpc.aviatrix_gateway.aviatrix_vpn_gateway
      allocate_new_eip:                      "off" => "on"
      vpc_net:                               "" => "subnet vaue"

**Comment by inc1t3Ful** [comment] 2019-03-07 23:48
Hi, what version Controller are you using, as well as the Aviatrix provider version?

The Aviatrix provider version and the Controller version must be matching in order to avoid any compatibility issues/ have the latest fixes

**Comment by infa-apatel** [comment] 2019-03-08 00:00
controller version 4.0.653.  Avatrix provier, I pulled today.

**Comment by inc1t3Ful** [comment] 2019-03-08 00:07
Thanks for the info. The Controller version you listed is incompatible with the current Aviatrix provider.

You would have to downgrade the Aviatrix provider version to 4.0, which is available on the 4.0 branch. https://github.com/AviatrixSystems/terraform-provider-aviatrix/tree/UserConnect-4.0

The other possibility is to upgrade your Controller to the latest patch of 4.1.981. However, upgrading the controller may disrupt your deployed network, so I would suggest against this for now.

**Comment by infa-apatel** [comment] 2019-03-08 00:16
controller is hard to upgrade, lot of process to go through :)

Trying to use the repository you gave, not working:
$ git clone "https://github.com/AviatrixSystems/terraform-provider-aviatrix/tree/UserConnect-4.0"
Cloning into 'UserConnect-4.0'...
fatal: repository 'https://github.com/AviatrixSystems/terraform-provider-aviatrix/tree/UserConnect-4.0/' not found

**Comment by infa-apatel** [comment] 2019-03-08 00:20
ignore, I got it.  I didn't specify the branch

**Comment by infa-apatel** [comment] 2019-03-08 00:25
Still having the same issue even with 4.0 branch you pointed out

**Comment by inc1t3Ful** [comment] 2019-03-08 01:01
This has been a known issue and has been fixed in Controller 4.1 and master branch.
We will port the fix onto 4.0 and update here. Thanks!

for internal use: id = 8557

**Comment by infa-apatel** [comment] 2019-03-14 14:30
Thanks, is the fix ported to 4.0?

**Comment by inc1t3Ful** [comment] 2019-03-14 17:57
Hi, the fix is ETA a week. We will update here as soon as possible. Thanks!

**Comment by inc1t3Ful** [comment] 2019-03-19 00:02
Hi, unfortunately, we could not reproduce the issue. However, there is a manual workaround. In the corresponding terraform.tfstate, you can manually input in the correct subnet value in the "vpc_net" parameter and save. 

Running 'terraform refresh' or 'apply' should yield no diff issues then.

**Closed** 2019-03-19 00:07 UTC

**Comment by infa-apatel** [comment] 2019-03-19 01:45
Hi, 

The workaround is not that easy for us.  We have over 55 environments already there and adding more.  Changing this value will be very difficult for each state file.

**Comment by arvindsree** [comment] 2019-03-19 04:10
What originally corrupted the state was using the master branch on the older controller version 4.0. Only  the controller version 4.1 has the logic to recover the state. So unfortunately, no fix on the provider can fix the state file. If it had been created from 4.0 branch provider, you would not run into this. Modifying the tfstate file is the only way as of now. The other option is to upgrade your controller.
