### ISSUE TITLE
Gateway: IAM role not attached to NLB

### ISSUE THREAD

**Issue by katiegamanji** [AviatrixSystems/terraform-provider-aviatrix#33] opened 2018-08-24 12:08 UTC
Hello, 

Currently we are trying to Terraform the creation of a gateway. However, if we do create the gateway manually or via Terraform, it ends up with a `down` state. 

While debugging the issue, we have noticed that the no IAM role is attached to the gateway instance. After adding it manually, everything worked as expected. 

**Question:** How can we attach the IAM role to the getaways via Terraform?

**Notes:**

Current version of Aviatrix controller: 3.4
Lb type: network  (as supposed to `classic` LB in v3.3)

**Comment by arvindsree** [comment] 2018-09-18 21:35
Cannot reproduce this. This does not look like it is related to the terraform provider. This is being tracked in support 7229 ticket. Closing this for now

**Closed by arvindsree** 2018-09-18 21:35 UTC
